### ISSUE TITLE
반응형 레이아웃 CSS수정

### ISSUE THREAD

**Issue by swgvenghy** [MARU-EGG/MARU_EGG_FE#31]
전체적으로 반응형 디자인 CSS가 모호합니다. 우선순위는 다음과 같습니다.
1. 데스크탑에서의 레이아웃 설정
2.데스크탑에서의 실제 글자크기 확인
3. 모바일 환경 대비 반응형 CSS설정

**Comment by sangmaaaaan** [comment]
issue해결
