### ISSUE TITLE
답변 출처 부분 CSS

### ISSUE THREAD

**Issue by sangmaaaaan** [MARU-EGG/MARU_EGG_FE#54]
<img width="573" alt="스크린샷 2024-10-02 오전 5 01 51" src="https://github.com/user-attachments/assets/e2e20dc8-4694-4b45-b967-ded51e5d415a">

답변 출처 부분 중 link부분만 부모 CSS에 종속되지 않는문제가 있습니다..
아직 미해결

**Comment by swgvenghy** [comment]
https://github.com/MARU-EGG/MARU_EGG_FE/pull/55

해결이요~
